"""pregnancy profiles

Revision ID: 1361e0c91ea9
Revises: d10f3895180f
Create Date: 2026-09-08 21:19:21.507885
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1361e0c91ea9'
down_revision: Union[str, None] = 'd10f3895180f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pregnancy_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('lmp_date', sa.Date(), nullable=True),
    sa.Column('edd', sa.Date(), nullable=True),
    sa.Column('edd_source', sa.String(length=20), nullable=True),
    sa.Column('ultrasound_date', sa.Date(), nullable=True),
    sa.Column('ultrasound_ga_days', sa.Integer(), nullable=True),
    sa.Column('baby_sex', sa.String(length=12), nullable=True),
    sa.Column('gravida', sa.Integer(), nullable=True),
    sa.Column('para', sa.Integer(), nullable=True),
    sa.Column('history_notes', sa.Text(), nullable=True),
    sa.Column('risk_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pregnancy_profiles')
    # ### end Alembic commands ###
