"""conversation stage + followup_plan

Revision ID: c843965d0aa9
Revises: ca2888f2385e
Create Date: 2026-09-08 19:57:04.800979
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c843965d0aa9'
down_revision: Union[str, None] = 'ca2888f2385e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('stage', sa.String(length=20), nullable=True))
    op.add_column('conversations', sa.Column('followup_plan', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'followup_plan')
    op.drop_column('conversations', 'stage')
    # ### end Alembic commands ###
