"""push subscriptions + scheduled followups

Revision ID: d10f3895180f
Revises: c843965d0aa9
Create Date: 2026-09-08 20:57:12.215578
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd10f3895180f'
down_revision: Union[str, None] = 'c843965d0aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_table('scheduled_followups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('topics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('generated_message', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_followups_due_at'), 'scheduled_followups', ['due_at'], unique=False)
    op.create_index(op.f('ix_scheduled_followups_status'), 'scheduled_followups', ['status'], unique=False)
    op.add_column('patients', sa.Column('timezone', sa.String(length=64), nullable=True))
    op.add_column('patients', sa.Column('followups_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'followups_enabled')
    op.drop_column('patients', 'timezone')
    op.drop_index(op.f('ix_scheduled_followups_status'), table_name='scheduled_followups')
    op.drop_index(op.f('ix_scheduled_followups_due_at'), table_name='scheduled_followups')
    op.drop_table('scheduled_followups')
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
